import { WeddingFullData } from '../types';

export const DEMO_WEDDING_DATA: WeddingFullData = {
  wedding: {
    id: 'demo-wedding-001',
    owner_id: 'demo-user-001',
    slug: 'vishnu-vijisha',
    title: 'Vishnu & Vijisha — Wedding Invitation',
    bride_name: 'Vijisha',
    bride_malayalam_name: 'വിജീഷ',
    groom_name: 'Vishnu',
    groom_malayalam_name: 'വിഷ്ണു',
    wedding_date: '2026-12-27',
    wedding_time: '10:30 AM',
    location: 'Thrissur, Kerala, India',
    location_malayalam: 'തൃശ്ശൂർ, കേരളം',
    venue_name: 'Gokulam Grand Auditorium & Temple Premises',
    venue_address: 'West Fort Road, Near West Bus Stand, Thrissur, Kerala 680004',
    google_maps_url: 'https://maps.google.com/?q=Thrissur+Kerala',
    bride_photo_url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
    groom_photo_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    couple_photo_url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
    hero_subtitle: 'Together with our families, we invite you to celebrate our wedding',
    hero_subtitle_malayalam: 'ഞങ്ങളുടെ മാംഗല്യ നിമിഷങ്ങൾക്ക് സാക്ഷിയാകുവാൻ ഏവരെയും ഹൃദയപൂർവ്വം ക്ഷണിക്കുന്നു',
    story_title: 'Our Journey of Love',
    story_text: 'Two hearts, two families, one beautiful beginning. With the divine blessings of Almighty and our beloved elders, we step into our new life together. Your gracious presence and prayers will make our celebration truly complete.',
    story_malayalam_text: 'രണ്ട് മനസ്സുകൾ, രണ്ട് കുടുംബങ്ങൾ, ഒരു സുന്ദരമായ തുടക്കം. ഗുരുഭൂതന്മാരുടെയും മുതിർന്നവരുടെയും അനുഗ്രഹത്തോടെ ഞങ്ങൾ ഒന്നാകുന്ന ഈ സുദിനത്തിൽ നിങ്ങളുടെ സാന്നിധ്യവും പ്രാർത്ഥനയും ഞങ്ങൾ ആഗ്രഹിക്കുന്നു.',
    status: 'published',
    is_password_protected: false,
    passcode: '',
    theme_id: 'kerala-traditional',
    music_url: 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=indian-wedding-flute-11234.mp3',
    music_enabled: true,
    opening_envelope_enabled: true,
    og_image_url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
    seo_title: 'Vishnu & Vijisha — Hindu Wedding Invitation',
    seo_description: 'We cordially invite you to celebrate the auspicious wedding of Vishnu & Vijisha on 27 December 2026 in Thrissur, Kerala.',
    gift_blessing_text: 'Your presence, blessings, and warm wishes are the greatest gifts we could ever ask for!',
    upi_id: 'vishnu.vijisha@upi',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  sections: [
    { id: 'sec-1', wedding_id: 'demo-wedding-001', section_type: 'hero', title: 'Hero Banner', title_malayalam: 'സ്വാഗതം', enabled: true, display_order: 1 },
    { id: 'sec-2', wedding_id: 'demo-wedding-001', section_type: 'story', title: 'Couple Story', title_malayalam: 'സ്നേഹകഥ', enabled: true, display_order: 2 },
    { id: 'sec-3', wedding_id: 'demo-wedding-001', section_type: 'countdown', title: 'Countdown', title_malayalam: 'സുദിനത്തിലേക്ക്', enabled: true, display_order: 3 },
    { id: 'sec-4', wedding_id: 'demo-wedding-001', section_type: 'events', title: 'Auspicious Ceremonies', title_malayalam: 'ചടങ്ങുകൾ', enabled: true, display_order: 4 },
    { id: 'sec-5', wedding_id: 'demo-wedding-001', section_type: 'venue', title: 'Venue & Directions', title_malayalam: 'വേദി', enabled: true, display_order: 5 },
    { id: 'sec-6', wedding_id: 'demo-wedding-001', section_type: 'gallery', title: 'Pre-Wedding Memories', title_malayalam: 'ചിത്രശാല', enabled: true, display_order: 6 },
    { id: 'sec-7', wedding_id: 'demo-wedding-001', section_type: 'family', title: 'With Elders\' Blessings', title_malayalam: 'അനുഗ്രഹങ്ങളോടെ', enabled: true, display_order: 7 },
    { id: 'sec-8', wedding_id: 'demo-wedding-001', section_type: 'dress_code', title: 'Dress Code', title_malayalam: 'വസ്ത്രധാരണം', enabled: true, display_order: 8 },
    { id: 'sec-9', wedding_id: 'demo-wedding-001', section_type: 'rsvp', title: 'RSVP', title_malayalam: 'സാന്നിധ്യം അറിയിക്കുക', enabled: true, display_order: 9 },
    { id: 'sec-10', wedding_id: 'demo-wedding-001', section_type: 'gifts', title: 'Blessings & Gifts', title_malayalam: 'ആശംസകൾ', enabled: true, display_order: 10 },
    { id: 'sec-11', wedding_id: 'demo-wedding-001', section_type: 'map', title: 'Interactive Map', title_malayalam: 'മാപ്പ്', enabled: true, display_order: 11 },
    { id: 'sec-12', wedding_id: 'demo-wedding-001', section_type: 'footer', title: 'Footer', title_malayalam: 'നന്ദി', enabled: true, display_order: 12 },
  ],
  events: [
    {
      id: 'ev-1',
      wedding_id: 'demo-wedding-001',
      title: 'Thaali Kettu / Wedding Ceremony',
      title_malayalam: 'മുഹൂർത്തം (താലികെട്ട്)',
      event_date: '2026-12-27',
      event_time: '10:30 AM - 11:45 AM',
      venue_name: 'Sri Krishna Temple Premises',
      venue_address: 'Guruvayur / Thrissur Temple Hall, Kerala',
      description: 'The sacred solemnization ceremony under divine traditional rituals, traditional Nadaswaram music, and garlanding.',
      description_malayalam: 'പരമ്പരാഗത ശൈലിയിലുള്ള വംഗമംഗല്യ ചടങ്ങുകൾ, മംഗള വാദ്യങ്ങളുടെ അകമ്പടിയോടെ മുഹൂർത്ത നിമിഷത്തിൽ നടക്കുന്നു.',
      google_maps_url: 'https://maps.google.com/?q=Guruvayur+Temple',
      image_url: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=800&q=80',
      dress_code: 'Traditional Kasavu Saree & Kerala Gold / White Mundu & Jubba',
      display_order: 1,
    },
    {
      id: 'ev-2',
      wedding_id: 'demo-wedding-001',
      title: 'Grand Wedding Reception & Feast (Sadhya)',
      title_malayalam: 'സൽക്കാരം & വിഭവസ സമൃദ്ധമായ സദ്യ',
      event_date: '2026-12-27',
      event_time: '12:15 PM - 03:30 PM & 06:00 PM Reception',
      venue_name: 'Gokulam Grand Auditorium',
      venue_address: 'West Fort Road, Thrissur, Kerala',
      description: 'Join us for an elaborate 28-item traditional Ela Sadhya followed by evening music celebration and photography.',
      description_malayalam: 'വിഭവസമൃദ്ധമായ ഇലസദ്യയും വൈകുന്നേരം സ്നേഹവിരുന്നും സംഗീത സന്ധ്യയും.',
      google_maps_url: 'https://maps.google.com/?q=Thrissur+Kerala',
      image_url: 'https://images.unsplash.com/photo-1544077960-604201fe74bc?auto=format&fit=crop&w=800&q=80',
      dress_code: 'Festive Ethnic Silk Sarees / Kurtas / Formal Suits',
      display_order: 2,
    },
    {
      id: 'ev-3',
      wedding_id: 'demo-wedding-001',
      title: 'Haldi & Sangeet Evening',
      title_malayalam: 'ഹൽദിയും സംഗീത സന്ധ്യയും',
      event_date: '2026-12-26',
      event_time: '04:30 PM Onwards',
      venue_name: 'Ancestral Heritage Courtyard',
      venue_address: 'Cherpu, Thrissur, Kerala',
      description: 'A cheerful celebration of turmeric blessing, laughter, folk dances, henna application, and festive music.',
      description_malayalam: 'മഞ്ഞളണിയൽ ചടങ്ങും മൈലാഞ്ചിയിടലും കുടുംബാംഗങ്ങളുടെ നൃത്തസംഗീത വിരുന്നുകളും.',
      google_maps_url: 'https://maps.google.com/?q=Cherpu+Thrissur',
      image_url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
      dress_code: 'Bright Yellow / Mustard Outfits & Floral Jewelry',
      display_order: 3,
    },
  ],
  family: [
    {
      id: 'fam-1',
      wedding_id: 'demo-wedding-001',
      name: 'Mr. Sadeeshbabu P K & Mrs. Indira Sadeeshbabu',
      relation: 'Parents of the Groom',
      family_side: 'groom',
      display_order: 1,
    },
    {
      id: 'fam-2',
      wedding_id: 'demo-wedding-001',
      name: 'Mr. Ramachandran Nair & Mrs. Radha Ramachandran',
      relation: 'Parents of the Bride',
      family_side: 'bride',
      display_order: 2,
    },
    {
      id: 'fam-3',
      wedding_id: 'demo-wedding-001',
      name: 'Dr. Anoop Sadeesh & Archana Anoop',
      relation: 'Brother & Sister-in-law (Groom\'s Family)',
      family_side: 'groom',
      display_order: 3,
    },
    {
      id: 'fam-4',
      wedding_id: 'demo-wedding-001',
      name: 'Major Varun Nair & Divya Varun',
      relation: 'Brother & Sister-in-law (Bride\'s Family)',
      family_side: 'bride',
      display_order: 4,
    },
    {
      id: 'fam-5',
      wedding_id: 'demo-wedding-001',
      name: 'Grandmother Smt. Karthyayani Amma',
      relation: 'Eldest Matriarch Blessing',
      family_side: 'blessings',
      display_order: 5,
    },
  ],
  gallery: [
    {
      id: 'gal-1',
      wedding_id: 'demo-wedding-001',
      image_url: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
      caption: 'Pre-wedding photoshoot in traditional Kerala attire',
      display_order: 1,
      is_cover: true,
    },
    {
      id: 'gal-2',
      wedding_id: 'demo-wedding-001',
      image_url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
      caption: 'Sacred temple moments',
      display_order: 2,
      is_cover: false,
    },
    {
      id: 'gal-3',
      wedding_id: 'demo-wedding-001',
      image_url: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
      caption: 'Golden sunset by the Backwaters',
      display_order: 3,
      is_cover: false,
    },
    {
      id: 'gal-4',
      wedding_id: 'demo-wedding-001',
      image_url: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=800&q=80',
      caption: 'Ring exchange and joyful smiles',
      display_order: 4,
      is_cover: false,
    },
    {
      id: 'gal-5',
      wedding_id: 'demo-wedding-001',
      image_url: 'https://images.unsplash.com/photo-1544077960-604201fe74bc?auto=format&fit=crop&w=800&q=80',
      caption: 'Traditional lotus floral arrangement',
      display_order: 5,
      is_cover: false,
    },
    {
      id: 'gal-6',
      wedding_id: 'demo-wedding-001',
      image_url: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80',
      caption: 'Warm smiles with family',
      display_order: 6,
      is_cover: false,
    },
  ],
  rsvps: [
    {
      id: 'rsvp-1',
      wedding_id: 'demo-wedding-001',
      guest_name: 'Unnikrishnan Nair',
      number_of_guests: 3,
      attending_status: 'attending',
      phone_number: '+91 98470 12345',
      message: 'Heartiest congratulations to Vishnu and Vijisha! Looking forward to the grand Kerala Sadhya!',
      meal_preference: 'Traditional Sadhya (Veg)',
      created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    },
    {
      id: 'rsvp-2',
      wedding_id: 'demo-wedding-001',
      guest_name: 'Priya Menon & Family',
      number_of_guests: 4,
      attending_status: 'attending',
      phone_number: '+91 94471 67890',
      message: 'Wishing both of you a lifetime of love and joy!',
      meal_preference: 'Traditional Sadhya (Veg)',
      created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
    {
      id: 'rsvp-3',
      wedding_id: 'demo-wedding-001',
      guest_name: 'Dr. Suresh Kumar',
      number_of_guests: 2,
      attending_status: 'not_attending',
      phone_number: '+91 98950 54321',
      message: 'Will be traveling abroad during those dates, sending our warmest blessings and love!',
      meal_preference: 'None',
      created_at: new Date(Date.now() - 86400000).toISOString(),
    },
  ],
};
