import { ThemeConfig } from '../types';

export const THEME_PRESETS: ThemeConfig[] = [
  {
    id: 'royal-maroon',
    name: 'Royal Maroon & Gold',
    primary_color: '#4A0E17',
    secondary_color: '#800020',
    background_color: '#FDFBF7',
    surface_color: '#FFFFFF',
    text_color: '#2C1810',
    muted_color: '#6E5D57',
    accent_color: '#D4AF37',
    border_color: '#E8D5B5',
    font_heading: "'Cormorant Garamond', 'Cinzel', serif",
    font_body: "'Outfit', sans-serif",
    decorative_style: 'mandala',
  },
  {
    id: 'kerala-traditional',
    name: 'Kerala Traditional (Kasavu & Gold)',
    primary_color: '#1E3A2B',
    secondary_color: '#8B0000',
    background_color: '#FFFDF5',
    surface_color: '#FFFFFF',
    text_color: '#1A241F',
    muted_color: '#5C6B62',
    accent_color: '#E6C200',
    border_color: '#E6D7A8',
    font_heading: "'Cormorant Garamond', 'Noto Serif Malayalam', serif",
    font_body: "'Outfit', sans-serif",
    decorative_style: 'temple',
  },
  {
    id: 'ivory-gold',
    name: 'Ivory & Amber Gold',
    primary_color: '#2B1E16',
    secondary_color: '#8C5E3B',
    background_color: '#FAF6F0',
    surface_color: '#FFFFFF',
    text_color: '#261C14',
    muted_color: '#7A6B5D',
    accent_color: '#C5A059',
    border_color: '#E3D7C5',
    font_heading: "'Cinzel', serif",
    font_body: "'Outfit', sans-serif",
    decorative_style: 'lotus',
  },
  {
    id: 'temple-elegance',
    name: 'Temple Elegance (Vermilion & Brass)',
    primary_color: '#8C2D19',
    secondary_color: '#A84024',
    background_color: '#FAF4EE',
    surface_color: '#FFFFFF',
    text_color: '#2B1B17',
    muted_color: '#6B544D',
    accent_color: '#CBA135',
    border_color: '#E6C6B8',
    font_heading: "'Cormorant Garamond', serif",
    font_body: "'Outfit', sans-serif",
    decorative_style: 'temple',
  },
  {
    id: 'minimal-luxury',
    name: 'Minimal Luxury (Obsidian & Gold)',
    primary_color: '#121212',
    secondary_color: '#222222',
    background_color: '#0F0F10',
    surface_color: '#1C1C1E',
    text_color: '#F2F2F7',
    muted_color: '#98989D',
    accent_color: '#E5C158',
    border_color: '#2C2C2E',
    font_heading: "'Cinzel', serif",
    font_body: "'Outfit', sans-serif",
    decorative_style: 'mandala',
  },
  {
    id: 'floral-romance',
    name: 'Floral Romance (Sage & Blush)',
    primary_color: '#2D4A3E',
    secondary_color: '#C08573',
    background_color: '#F8F6F0',
    surface_color: '#FFFFFF',
    text_color: '#1E2C25',
    muted_color: '#63736A',
    accent_color: '#D4A373',
    border_color: '#E0D6C8',
    font_heading: "'Cormorant Garamond', serif",
    font_body: "'Outfit', sans-serif",
    decorative_style: 'floral',
  },
];

export const getThemeById = (id: string): ThemeConfig => {
  return THEME_PRESETS.find((t) => t.id === id) || THEME_PRESETS[0];
};
